import React from 'react';
import Head from '@docusaurus/Head';
import Layout from '@theme/Layout';
import useDocusaurusContext from '@docusaurus/useDocusaurusContext';
import { CookbookHome } from '@site/src/components';
import { AI_COOKBOOK_OG_IMAGE_PATH } from '@site/src/constants/aiCookbookOgImage';
import { AI_COOKBOOK_BLURB } from '@site/src/constants/aiCookbookBlurb';

export default function CookbookLanding() {
  const { siteConfig } = useDocusaurusContext();
  const ogImageUrl = `${siteConfig.url}${AI_COOKBOOK_OG_IMAGE_PATH}`;

  return (
    <Layout title="AI Cookbook" description={AI_COOKBOOK_BLURB}>
      {/* Markdown + og:image both generated by plugins/cookbook-index's
          postBuild hook — see readme/MARKDOWN_PIPELINE.md. This page is a plain
          React page, not an MDX doc, so it's outside the automatic per-doc
          pipeline and needs these tags set explicitly. */}
      <Head>
        <link rel="alternate" type="text/markdown" href="/ai/cookbook.md" title="AI Cookbook" />
        <meta property="og:image" content={ogImageUrl} />
        <meta name="twitter:image" content={ogImageUrl} />
      </Head>
      <CookbookHome />
    </Layout>
  );
}
