StylesPath = "vale/styles"

MinAlertLevel = suggestion

[*.{md,mdx}]
BasedOnStyles = Temporal

; Only enable the two rules we want in CI
Temporal.badwords = NO
Temporal.complexwords = NO
Temporal.programming = NO
Temporal.WordList = NO

; ignore MDX custom heading-ID comments, e.g. {/* #ha-worker-patterns */}
TokenIgnores = (\{/\*[^\n]*?\*/\})

[formats]
mdx = md
