module.exports = {
  documentation: [
    'index',
    'quickstarts',
    {
      type: 'category',
      label: 'Evaluate',
      collapsed: true,
      link: {
        type: 'doc',
        id: 'evaluate/index',
      },
      items: [
        'evaluate/why-temporal',
        'evaluate/understanding-temporal',
        {
          type: 'category',
          label: 'Features',
          collapsed: true,
          link: {
            type: 'doc',
            id: 'evaluate/development-production-features/index',
          },
          items: [
            'evaluate/development-production-features/core-application',
            'evaluate/development-production-features/failure-detection',
            'evaluate/development-production-features/throughput-composability',
            'evaluate/development-production-features/nexus',
            'evaluate/development-production-features/workflow-message-passing',
            'evaluate/development-production-features/debugging',
            'evaluate/development-production-features/interrupt-workflow',
            'evaluate/development-production-features/testing-suite',
            'evaluate/development-production-features/observability',
            'evaluate/development-production-features/data-encryption',
            'evaluate/development-production-features/schedules',
            'evaluate/development-production-features/cloud-automation',
            'evaluate/development-production-features/low-latency',
            'evaluate/development-production-features/multi-tenancy',
            {
              type: 'category',
              label: 'Product release stages',
              collapsed: true,
              link: {
                type: 'doc',
                id: 'evaluate/development-production-features/release-stages',
              },
              items: [
                {
                  type: 'link',
                  label: 'Change-log',
                  href: 'https://temporal.io/change-log',
                },
              ],
            },
          ],
        },
        {
          type: 'category',
          label: 'Temporal Cloud',
          collapsed: true,
          link: {
            type: 'doc',
            id: 'evaluate/temporal-cloud/overview',
          },
          items: [
            'evaluate/temporal-cloud/security',
            'evaluate/temporal-cloud/service-availability',
            'evaluate/temporal-cloud/regions',
            'evaluate/temporal-cloud/limits',
            'evaluate/temporal-cloud/sla',
            'evaluate/temporal-cloud/pricing',
            'evaluate/temporal-cloud/actions',
            'evaluate/temporal-cloud/support',
          ],
        },
        'security',
        'evaluate/use-cases-design-patterns',
      ],
    },
    {
      type: 'category',
      label: 'Develop',
      collapsed: true,
      link: {
        type: 'doc',
        id: 'develop/index',
      },
      items: [
        {
          type: 'category',
          label: 'Go SDK',
          collapsed: true,
          link: {
            type: 'doc',
            id: 'develop/go/index',
          },
          items: [
            'develop/go/set-up-your-local-go',
            'develop/go/core-application',
            'develop/go/temporal-client',
            'develop/go/go-sdk-multithreading',
            'develop/go/namespaces',
            'develop/go/testing-suite',
            'develop/go/failure-detection',
            'develop/go/message-passing',
            'develop/go/cancellation',
            'develop/go/asynchronous-activity-completion',
            'develop/go/versioning',
            'develop/go/observability',
            'develop/go/benign-exceptions',
            'develop/go/enriching-ui',
            'develop/go/debugging',
            'develop/go/schedules',
            'develop/go/converters-and-encryption',
            'develop/go/timers',
            'develop/go/nexus',
            'develop/go/child-workflows',
            'develop/go/continue-as-new',
            'develop/go/side-effects',
            'develop/go/selectors',
            'develop/go/sessions',
          ],
        },
        {
          type: 'category',
          label: 'Java SDK',
          collapsed: true,
          link: {
            type: 'doc',
            id: 'develop/java/index',
          },
          items: [
            'develop/java/set-up-your-local-java',
            'develop/java/core-application',
            'develop/java/temporal-client',
            'develop/java/namespaces',
            'develop/java/testing-suite',
            'develop/java/failure-detection',
            'develop/java/message-passing',
            'develop/java/cancellation',
            'develop/java/asynchronous-activity-completion',
            'develop/java/versioning',
            'develop/java/observability',
            'develop/java/benign-exceptions',
            'develop/java/enriching-ui',
            'develop/java/debugging',
            'develop/java/schedules',
            'develop/java/converters-and-encryption',
            'develop/java/timers',
            'develop/java/nexus',
            'develop/java/child-workflows',
            'develop/java/continue-as-new',
            'develop/java/side-effects',
            'develop/java/spring-boot-integration',
          ],
        },
        {
          type: 'category',
          label: 'PHP SDK',
          collapsed: true,
          link: {
            type: 'doc',
            id: 'develop/php/index',
          },
          items: [
            'develop/php/core-application',
            'develop/php/temporal-client',
            'develop/php/testing-suite',
            'develop/php/failure-detection',
            'develop/php/message-passing',
            'develop/php/cancellation',
            'develop/php/asynchronous-activity-completion',
            'develop/php/versioning',
            'develop/php/observability',
            'develop/php/enriching-ui',
            'develop/php/debugging',
            'develop/php/schedules',
            'develop/php/timers',
            'develop/php/side-effects',
            'develop/php/child-workflows',
            'develop/php/continue-as-new',
          ],
        },
        {
          type: 'category',
          label: 'Python SDK',
          collapsed: true,
          link: {
            type: 'doc',
            id: 'develop/python/index',
          },
          items: [
            'develop/python/set-up-your-local-python',
            'develop/python/core-application',
            'develop/python/temporal-client',
            'develop/python/python-sdk-sandbox',
            'develop/python/python-sdk-sync-vs-async',
            'develop/python/testing-suite',
            'develop/python/failure-detection',
            'develop/python/message-passing',
            'develop/python/cancellation',
            'develop/python/asynchronous-activity-completion',
            'develop/python/versioning',
            'develop/python/observability',
            'develop/python/benign-exceptions',
            'develop/python/enriching-ui',
            'develop/python/debugging',
            'develop/python/schedules',
            'develop/python/converters-and-encryption',
            'develop/python/timers',
            'develop/python/nexus',
            'develop/python/child-workflows',
            'develop/python/continue-as-new',
            'develop/python/interceptors',
            {
              type: 'category',
              label: 'Integrations',
              collapsed: true,
              link: {
                type: 'doc',
                id: 'develop/python/integrations/index',
              },
              items: ['develop/python/integrations/braintrust'],
            },
          ],
        },
        {
          type: 'category',
          label: 'TypeScript SDK',
          collapsed: true,
          link: {
            type: 'doc',
            id: 'develop/typescript/index',
          },
          items: [
            'develop/typescript/set-up-your-local-typescript',
            'develop/typescript/core-application',
            'develop/typescript/temporal-client',
            'develop/typescript/namespaces',
            'develop/typescript/testing-suite',
            'develop/typescript/failure-detection',
            'develop/typescript/message-passing',
            'develop/typescript/cancellation',
            'develop/typescript/asynchronous-activity-completion',
            'develop/typescript/versioning',
            'develop/typescript/observability',
            'develop/typescript/benign-exceptions',
            'develop/typescript/enriching-ui',
            'develop/typescript/debugging',
            'develop/typescript/schedules',
            'develop/typescript/converters-and-encryption',
            'develop/typescript/timers',
            'develop/typescript/nexus',
            'develop/typescript/child-workflows',
            'develop/typescript/continue-as-new',
            'develop/typescript/interceptors',
            {
              type: 'category',
              label: 'Integrations',
              collapsed: true,
              link: {
                type: 'doc',
                id: 'develop/typescript/integrations/index',
              },
              items: ['develop/typescript/integrations/ai-sdk'],
            },
          ],
        },
        {
          type: 'category',
          label: '.NET SDK',
          collapsed: true,
          link: {
            type: 'doc',
            id: 'develop/dotnet/index',
          },
          items: [
            'develop/dotnet/set-up-your-local-dotnet',
            'develop/dotnet/core-application',
            'develop/dotnet/temporal-client',
            'develop/dotnet/testing-suite',
            'develop/dotnet/failure-detection',
            'develop/dotnet/message-passing',
            'develop/dotnet/cancellation',
            'develop/dotnet/asynchronous-activity',
            'develop/dotnet/versioning',
            'develop/dotnet/observability',
            'develop/dotnet/benign-exceptions',
            'develop/dotnet/enriching-ui',
            'develop/dotnet/debugging',
            'develop/dotnet/schedules',
            'develop/dotnet/converters-and-encryption',
            'develop/dotnet/durable-timers',
            'develop/dotnet/nexus',
            'develop/dotnet/child-workflows',
            'develop/dotnet/continue-as-new',
          ],
        },
        {
          type: 'category',
          label: 'Ruby SDK',
          collapsed: true,
          link: {
            type: 'doc',
            id: 'develop/ruby/index',
          },
          items: [
            'develop/ruby/set-up-local-ruby',
            'develop/ruby/core-application',
            'develop/ruby/temporal-client',
            'develop/ruby/testing-suite',
            'develop/ruby/failure-detection',
            'develop/ruby/message-passing',
            'develop/ruby/interrupt-workflow',
            'develop/ruby/asynchronous-activity',
            'develop/ruby/versioning',
            'develop/ruby/observability',
            'develop/ruby/benign-exceptions',
            'develop/ruby/enriching-ui',
            'develop/ruby/debugging',
            'develop/ruby/schedules',
            'develop/ruby/converters-and-encryption',
            'develop/ruby/rails-integration',
            'develop/ruby/durable-timers',
            'develop/ruby/child-workflows',
            'develop/ruby/continue-as-new',
          ],
        },
        'develop/environment-configuration',
        'develop/activity-retry-simulator',
        'develop/worker-performance',
        'develop/safe-deployments',
        'develop/plugins-guide',
      ],
    },
    {
      type: 'category',
      label: 'Temporal Cloud',
      collapsed: true,
      link: {
        type: 'doc',
        id: 'cloud/index',
      },
      items: [
        {
          type: 'category',
          label: 'Get started with Cloud',
          collapsed: false,
          link: {
            type: 'doc',
            id: 'cloud/get-started/index',
          },
          items: [
            'cloud/get-started/namespaces',
            'cloud/get-started/api-keys',
            'cloud/get-started/certificates',
            'cloud/get-started/billing-and-cost',
          ],
        },
        {
          type: 'category',
          label: 'Account access',
          collapsed: false,
          link: {
            type: 'doc',
            id: 'cloud/manage-access/index',
          },
          items: [
            'cloud/get-started/users',
            'cloud/get-started/user-groups',
            'cloud/get-started/service-accounts',
            'cloud/saml',
            'cloud/scim',
          ],
        },
        {
          type: 'category',
          label: 'Metrics',
          collapsed: true,
          link: {
            type: 'doc',
            id: 'cloud/metrics/index',
          },
          items: [
            {
              type: 'category',
              label: 'OpenMetrics',
              collapsed: true,
              link: {
                type: 'doc',
                id: 'cloud/metrics/openmetrics/index',
              },
              items: [
                'cloud/metrics/openmetrics/metrics-integrations',
                'cloud/metrics/openmetrics/migration-guide',
                'cloud/metrics/openmetrics/api-reference',
                'cloud/metrics/openmetrics/metrics-reference',
              ],
            },
            {
              type: 'category',
              label: 'PromQL',
              collapsed: true,
              link: {
                type: 'doc',
                id: 'cloud/metrics/promql',
              },
              items: [
                'cloud/metrics/general-setup',
                'cloud/metrics/reference',
                'cloud/metrics/datadog',
                'cloud/metrics/prometheus-grafana',
              ],
            },
          ],
        },
        {
          type: 'category',
          label: 'Connectivity',
          collapsed: true,
          link: {
            type: 'doc',
            id: 'cloud/connectivity/index',
          },
          items: [
            'cloud/connectivity/aws-connectivity',
            'cloud/connectivity/gcp-connectivity',
            'cloud/connectivity/ip-addresses',
          ],
        },
        {
          type: 'category',
          label: 'High Availability',
          collapsed: true,
          link: {
            type: 'doc',
            id: 'cloud/high-availability/index',
          },
          items: [
            'cloud/high-availability/enable',
            'cloud/high-availability/monitoring',
            'cloud/high-availability/failovers',
            'cloud/high-availability/ha-connectivity',
          ],
        },
        'cloud/rpo-rto',
        {
          type: 'category',
          label: 'Temporal Nexus',
          collapsed: true,
          link: {
            type: 'doc',
            id: 'cloud/nexus/index',
          },
          items: [
            'cloud/nexus/security',
            'cloud/nexus/observability',
            'cloud/nexus/latency-availability',
            'cloud/nexus/limits',
            'cloud/nexus/pricing',
          ],
        },
        {
          type: 'category',
          label: 'Migrate',
          collapsed: true,
          link: {
            type: 'doc',
            id: 'cloud/migrate/index',
          },
          items: ['cloud/migrate/automated', 'cloud/migrate/manual', 'cloud/migrate/migrate-within-cloud'],
        },
        'cloud/capacity-modes',
        'cloud/worker-health',
        'cloud/service-health',
        'cloud/notifications',
        'cloud/operation-api',
        'cloud/terraform-provider',
        {
          type: 'category',
          label: 'Export',
          collapsed: true,
          link: {
            type: 'doc',
            id: 'cloud/export',
          },
          items: ['cloud/aws-export-s3', 'cloud/gcp-export-gcs'],
        },
        {
          type: 'category',
          label: 'Audit Logging',
          collapsed: true,
          link: {
            type: 'doc',
            id: 'cloud/audit-logs',
          },
          items: [
            'cloud/audit-logs-aws',
            'cloud/audit-logs-gcp', // pre-release
          ],
        },
        {
          type: 'category',
          label: 'CLI (tcld)',
          collapsed: true,
          link: {
            type: 'doc',
            id: 'cloud/tcld/index',
          },
          items: [
            'cloud/tcld/account',
            'cloud/tcld/apikey',
            'cloud/tcld/feature',
            'cloud/tcld/generate-certificates',
            'cloud/tcld/login',
            'cloud/tcld/logout',
            'cloud/tcld/namespace',
            'cloud/tcld/nexus',
            'cloud/tcld/request',
            'cloud/tcld/user',
            'cloud/tcld/user-group',
            'cloud/tcld/version',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Deploy to production',
      collapsed: true,
      link: {
        type: 'doc',
        id: 'production-deployment/index',
      },
      items: [
        {
          type: 'category',
          label: 'Self-host',
          collapsed: true,
          link: {
            type: 'doc',
            id: 'production-deployment/self-hosted-guide/index',
          },
          items: [
            'production-deployment/self-hosted-guide/deployment',
            'production-deployment/self-hosted-guide/checklist',
            'production-deployment/self-hosted-guide/defaults',
            'production-deployment/self-hosted-guide/namespaces',
            'production-deployment/self-hosted-guide/security',
            'production-deployment/self-hosted-guide/monitoring',
            'production-deployment/self-hosted-guide/visibility',
            'production-deployment/self-hosted-guide/upgrade-server',
            'production-deployment/self-hosted-guide/archival',
            'production-deployment/self-hosted-guide/multi-cluster-replication',
            'production-deployment/self-hosted-guide/nexus',
            'production-deployment/self-hosted-guide/server-frontend-api-reference',
          ],
        },
        {
          type: 'category',
          label: 'Worker deployments',
          collapsed: true,
          link: {
            type: 'doc',
            id: 'production-deployment/worker-deployments/index',
          },
          items: [
            'production-deployment/worker-deployments/worker-versioning',
            'production-deployment/worker-deployments/kubernetes-controller',
            'production-deployment/worker-deployments/deploy-workers-to-aws-eks',
          ],
        },
        'production-deployment/data-encryption',
      ],
    },
    {
      type: 'category',
      label: 'CLI (temporal)',
      collapsed: true,
      link: {
        type: 'doc',
        id: 'cli/index',
      },
      items: [
        'cli/setup-cli',
        'cli/activity',
        'cli/batch',
        'cli/config',
        'cli/env',
        'cli/operator',
        'cli/schedule',
        'cli/server',
        'cli/task-queue',
        'cli/worker',
        'cli/workflow',
      ],
    },
    {
      type: 'category',
      label: 'References',
      collapsed: true,
      link: {
        type: 'doc',
        id: 'references/index',
      },
      items: [
        'references/cluster-metrics',
        'references/commands',
        'references/configuration',
        'references/dynamic-configuration',
        'references/errors',
        'references/events',
        'references/client-environment-configuration',
        'references/failures',
        'references/operation-list',
        'references/sdk-metrics',
        'references/server-options',
        'references/web-ui-configuration',
        'references/web-ui-environment-variables',
      ],
    },
    {
      type: 'category',
      label: 'Troubleshooting',
      collapsed: true,
      link: {
        type: 'doc',
        id: 'troubleshooting/index',
      },
      items: [
        'troubleshooting/blob-size-limit-error',
        'troubleshooting/deadline-exceeded-error',
        'troubleshooting/last-connection-error',
        'troubleshooting/performance-bottlenecks',
      ],
    },
    {
      type: 'category',
      label: 'Best Practices',
      collapsed: true,
      link: {
        type: 'doc',
        id: 'best-practices/index',
      },
      items: [
        'best-practices/managing-namespace',
        'best-practices/managing-aps-limits',
        'best-practices/cloud-access-control',
        'best-practices/security-controls',
        'best-practices/worker',
        'best-practices/knowledge-hub',
      ],
    },
    {
      type: 'category',
      label: 'Encyclopedia',
      collapsed: true,
      link: {
        type: 'doc',
        id: 'encyclopedia/index',
      },
      items: [
        'encyclopedia/temporal',
        'encyclopedia/temporal-sdks',
        {
          type: 'category',
          label: 'Workflows',
          collapsed: true,
          link: {
            type: 'doc',
            id: 'encyclopedia/workflow/workflow-overview',
          },
          items: [
            'encyclopedia/workflow/workflow-definition',
            {
              type: 'category',
              label: 'Workflow Execution',
              collapsed: true,
              link: {
                type: 'doc',
                id: 'encyclopedia/workflow/workflow-execution/workflow-execution',
              },
              items: [
                'encyclopedia/workflow/workflow-execution/workflowid-runid',
                'encyclopedia/workflow/workflow-execution/event',
                'encyclopedia/workflow/workflow-execution/continue-as-new',
                'encyclopedia/workflow/workflow-execution/limits',
                'encyclopedia/workflow/workflow-execution/timers-delays',
              ],
            },
            'encyclopedia/workflow/dynamic-handler',
            'encyclopedia/workflow/workflow-schedule',
            'encyclopedia/workflow/cron-job',
            'encyclopedia/workflow/patching',
          ],
        },
        {
          type: 'category',
          label: 'Activities',
          collapsed: true,
          link: {
            type: 'doc',
            id: 'encyclopedia/activities/activities',
          },
          items: [
            'encyclopedia/activities/activity-definition',
            'encyclopedia/activities/activity-execution',
            'encyclopedia/activities/local-activity',
          ],
        },
        {
          type: 'category',
          label: 'Detecting application failures',
          collapsed: true,
          link: {
            type: 'doc',
            id: 'encyclopedia/detecting-application-failures',
          },
          items: [
            'encyclopedia/detecting-activity-failures',
            'encyclopedia/detecting-workflow-failures',
            'encyclopedia/retry-policies',
          ],
        },
        {
          type: 'category',
          label: 'Workers',
          collapsed: true,
          link: {
            type: 'doc',
            id: 'encyclopedia/workers/workers',
          },
          items: [
            'encyclopedia/workers/tasks',
            'encyclopedia/workers/task-queues',
            'encyclopedia/workers/task-queue-naming',
            'encyclopedia/workers/task-routing-worker-sessions',
            'encyclopedia/workers/sticky-execution',
            'encyclopedia/workers/worker-shutdown',
            'encyclopedia/workers/worker-versioning',
          ],
        },
        {
          type: 'category',
          label: 'Event History',
          collapsed: true,
          link: {
            type: 'doc',
            id: 'encyclopedia/event-history/event-history',
          },
          items: [
            'encyclopedia/event-history/event-history-go',
            'encyclopedia/event-history/event-history-dotnet',
            'encyclopedia/event-history/event-history-java',
            'encyclopedia/event-history/event-history-python',
            'encyclopedia/event-history/event-history-typescript',
          ],
        },
        {
          type: 'category',
          label: 'Workflow Message Passing',
          collapsed: true,
          link: {
            type: 'doc',
            id: 'encyclopedia/workflow-message-passing/workflow-message-passing',
          },
          items: [
            'encyclopedia/workflow-message-passing/sending-messages',
            'encyclopedia/workflow-message-passing/handling-messages',
          ],
        },
        {
          type: 'category',
          label: 'Child Workflows',
          collapsed: true,
          link: {
            type: 'doc',
            id: 'encyclopedia/child-workflows/child-workflows',
          },
          items: ['encyclopedia/child-workflows/parent-close-policy'],
        },
        {
          type: 'category',
          label: 'Visibility',
          collapsed: true,
          link: {
            type: 'doc',
            id: 'encyclopedia/visibility/visibility',
          },
          items: [
            'encyclopedia/visibility/dual-visibility',
            'encyclopedia/visibility/list-filter',
            'encyclopedia/visibility/search-attribute',
          ],
        },
        {
          type: 'category',
          label: 'Temporal Service',
          collapsed: true,
          link: {
            type: 'doc',
            id: 'encyclopedia/temporal-service/temporal-service',
          },
          items: [
            'encyclopedia/temporal-service/temporal-server',
            'encyclopedia/temporal-service/persistence',
            'encyclopedia/temporal-service/visibility',
            'encyclopedia/temporal-service/archival',
            'encyclopedia/temporal-service/temporal-service-configuration',
            'encyclopedia/temporal-service/multi-cluster-replication',
          ],
        },
        {
          type: 'category',
          label: 'Namespaces',
          collapsed: true,
          link: {
            type: 'doc',
            id: 'encyclopedia/namespaces/namespaces',
          },
          items: ['encyclopedia/namespaces/global-namespaces'],
        },
        {
          type: 'category',
          label: 'Temporal Nexus',
          collapsed: true,
          link: {
            type: 'doc',
            id: 'encyclopedia/nexus',
          },
          items: [
            'encyclopedia/nexus-endpoints',
            'encyclopedia/nexus-registry',
            'encyclopedia/nexus-services',
            'encyclopedia/nexus-operations',
            'encyclopedia/nexus-use-cases',
            'encyclopedia/nexus-execution-debugging',
            'encyclopedia/nexus-error-handling',
            'encyclopedia/nexus-metrics',
            'encyclopedia/nexus-security',
          ],
        },
        {
          type: 'category',
          label: 'Data Conversion',
          collapsed: true,
          link: {
            type: 'doc',
            id: 'encyclopedia/data-conversion/dataconversion',
          },
          items: [
            'encyclopedia/data-conversion/default-custom-data-converters',
            'encyclopedia/data-conversion/payload-converter',
            'encyclopedia/data-conversion/payload-codec',
            'encyclopedia/data-conversion/failure-converter',
            'encyclopedia/data-conversion/remote-data-encoding',
            'encyclopedia/data-conversion/codec-server',
            'encyclopedia/data-conversion/key-management',
          ],
        },
        'web-ui',
      ],
    },
    'glossary',
    'with-ai',
    // {
    //   type: "autogenerated",
    //   dirName: "./dev-guide", // '.' means the current docs folder
    // },
  ],
  tctl: [
    'tctl-v1/index',
    'tctl-v1/activity',
    'tctl-v1/admin',
    'tctl-v1/batch',
    'tctl-v1/cluster',
    'tctl-v1/dataconverter',
    'tctl-v1/namespace',
    'tctl-v1/schedule',
    'tctl-v1/taskqueue',
    'tctl-v1/workflow',
  ],
};
