import React from "react";
import { DocsTable, NewDocsCell, DocsTableRow } from '@site/src/components';

const operations = [
    { "operation": "ActivityRetryTimer", "description": "Internal Timer that schedules the retry of a failed Activity Execution.", "effect_of_throttling": "The Activity retry is delayed.", "is_background": "TRUE" },
    { "operation": "ActivityTimeout", "description": "Marks an Activity as timed out when its deadline passes.", "effect_of_throttling": "The Activity Task stays in flight longer and the timeout is delayed, which also delays any retry.", "is_background": "TRUE" },
    { "operation": "CompleteNexusOperation", "description": "Completes a Nexus Operation after the Worker responds.", "effect_of_throttling": "Cleanup and completion of the Nexus Operation are delayed.", "is_background": "FALSE" },
    { "operation": "CreateSchedule", "description": "Creates a Schedule.", "effect_of_throttling": "The Client receives a ResourceExhausted error, then backs off and retries.", "is_background": "FALSE" },
    { "operation": "CreateWorkflowRule", "description": "Adds a Worker Versioning rule for a Task Queue.", "effect_of_throttling": "Enforcement of the rule is delayed.", "is_background": "FALSE" },
    { "operation": "DeleteSchedule", "description": "Deletes a Schedule.", "effect_of_throttling": "The Schedule can keep running Actions briefly.", "is_background": "FALSE" },
    { "operation": "DeleteWorkerDeployment", "description": "Deletes a Worker Deployment record.", "effect_of_throttling": "Stale Worker Deployment metadata remains longer.", "is_background": "FALSE" },
    { "operation": "DeleteWorkerDeploymentVersion", "description": "Deletes one version from a Worker Deployment.", "effect_of_throttling": "The version appears valid until the task is processed.", "is_background": "FALSE" },
    { "operation": "DeleteWorkflowExecution", "description": "Permanently deletes a Workflow Execution's Event History and state.", "effect_of_throttling": "The data stays visible and storage is freed later.", "is_background": "FALSE" },
    { "operation": "DeleteWorkflowRule", "description": "Deletes a Worker Versioning rule.", "effect_of_throttling": "The rule stays in effect until the task is processed.", "is_background": "FALSE" },
    { "operation": "DeprecateNamespace", "description": "Marks a Namespace as deprecated.", "effect_of_throttling": "Clients still see the Namespace as active.", "is_background": "FALSE" },
    { "operation": "DescribeBatchOperation", "description": "Returns metadata for a batch operation.", "effect_of_throttling": "Reads from the Web UI and admin tools take longer.", "is_background": "FALSE" },
    { "operation": "DescribeDeployment", "description": "Returns details for a Worker Deployment.", "effect_of_throttling": "The response is delayed.", "is_background": "FALSE" },
    { "operation": "DescribeNamespace", "description": "Returns a Namespace's configuration.", "effect_of_throttling": "The response is delayed.", "is_background": "FALSE" },
    { "operation": "DescribeSchedule", "description": "Returns a Schedule's current state.", "effect_of_throttling": "The response is delayed.", "is_background": "FALSE" },
    { "operation": "DescribeTaskQueue", "description": "Returns statistics and configuration for a Task Queue.", "effect_of_throttling": "Monitoring dashboards lag.", "is_background": "FALSE" },
    { "operation": "DescribeWorkerDeployment", "description": "Returns details for a specific Worker Deployment.", "effect_of_throttling": "The response is delayed.", "is_background": "FALSE" },
    { "operation": "DescribeWorkerDeploymentVersion", "description": "Returns details for a specific Worker Deployment Version.", "effect_of_throttling": "The response is delayed.", "is_background": "FALSE" },
    { "operation": "DescribeWorkflowExecution", "description": "Returns summary information for a Workflow Execution.", "effect_of_throttling": "The Temporal CLI and diagnostic tools wait longer.", "is_background": "FALSE" },
    { "operation": "DescribeWorkflowRule", "description": "Returns a Worker Versioning rule.", "effect_of_throttling": "The response is delayed.", "is_background": "FALSE" },
    { "operation": "DispatchByEndpoint", "description": "Routes a Nexus Task to Workers by Nexus Endpoint name.", "effect_of_throttling": "Nexus Task routing latency increases.", "is_background": "FALSE" },
    { "operation": "DispatchByNamespaceAndTaskQueue", "description": "Routes a Nexus Task to Workers by Namespace and Task Queue.", "effect_of_throttling": "The Nexus Task starts later.", "is_background": "FALSE" },
    { "operation": "ExecuteMultiOperation", "description": "Runs several operations as one request, such as Update-With-Start.", "effect_of_throttling": "The request is delayed.", "is_background": "FALSE" },
    { "operation": "GetClusterInfo", "description": "Returns the Temporal Service's capabilities and versions.", "effect_of_throttling": "Temporal CLI and API calls take longer.", "is_background": "FALSE" },
    { "operation": "GetCurrentDeployment", "description": "Returns the current Worker Deployment.", "effect_of_throttling": "Rollout tooling sees stale information.", "is_background": "FALSE" },
    { "operation": "GetSearchAttributes", "description": "Lists custom Search Attribute definitions.", "effect_of_throttling": "SDK and Temporal CLI calls wait longer.", "is_background": "FALSE" },
    { "operation": "GetSystemInfo", "description": "Returns the Temporal Service's build and feature information.", "effect_of_throttling": "The response is delayed.", "is_background": "FALSE" },
    { "operation": "GetWorkerBuildIdCompatibility", "description": "Returns the Build ID compatibility sets for a Task Queue.", "effect_of_throttling": "Rollout decisions wait longer.", "is_background": "FALSE" },
    { "operation": "GetWorkerVersioningRules", "description": "Lists Worker Versioning rules.", "effect_of_throttling": "The response is delayed.", "is_background": "FALSE" },
    { "operation": "GetWorkflowExecutionHistory", "description": "Streams a Workflow Execution's Event History in order.", "effect_of_throttling": "Event History loads slowly in the Web UI and the Temporal CLI.", "is_background": "FALSE" },
    { "operation": "GetWorkflowExecutionHistoryReverse", "description": "Streams a Workflow Execution's Event History in reverse order.", "effect_of_throttling": "Event History loads slowly in the Web UI and the Temporal CLI.", "is_background": "FALSE" },
    { "operation": "ListNamespaces", "description": "Lists all Namespaces.", "effect_of_throttling": "Each page of results in the Web UI and the Temporal CLI loads more slowly.", "is_background": "FALSE" },
    { "operation": "ListScheduleMatchingTimes", "description": "Returns the upcoming times a Schedule will run.", "effect_of_throttling": "The preview takes longer.", "is_background": "FALSE" },
    { "operation": "ListTaskQueuePartitions", "description": "Lists the partitions of a Task Queue.", "effect_of_throttling": "Partition information lags.", "is_background": "FALSE" },
    { "operation": "ListWorkerDeployments", "description": "Lists all Worker Deployments.", "effect_of_throttling": "The response is delayed.", "is_background": "FALSE" },
    { "operation": "ListWorkflowRules", "description": "Lists all Worker Versioning rules.", "effect_of_throttling": "The response is delayed.", "is_background": "FALSE" },
    { "operation": "PatchSchedule", "description": "Applies a one-time change to a Schedule, such as triggering it or backfilling Actions.", "effect_of_throttling": "The change takes effect later.", "is_background": "FALSE" },
    { "operation": "PauseActivity", "description": "Pauses a running Activity.", "effect_of_throttling": "The Activity keeps running until the pause task is processed.", "is_background": "FALSE" },
    { "operation": "PollActivityTaskQueue", "description": "Worker long-poll for Activity Tasks.", "effect_of_throttling": "The poller receives a ResourceExhausted error, then backs off and retries, which slows Activity Task processing.", "is_background": "FALSE" },
    { "operation": "PollNexusTaskQueue", "description": "Worker long-poll for Nexus Tasks.", "effect_of_throttling": "The poller receives a ResourceExhausted error, then backs off and retries, which slows Nexus Task processing.", "is_background": "FALSE" },
    { "operation": "PollWorkflowExecutionUpdate", "description": "Client poll for the result of a Workflow Update.", "effect_of_throttling": "The Client waits longer for the result.", "is_background": "FALSE" },
    { "operation": "PollWorkflowTaskQueue", "description": "Worker long-poll for Workflow Tasks.", "effect_of_throttling": "The poller receives a ResourceExhausted error, then backs off and retries, which slows Workflow progress.", "is_background": "FALSE" },
    { "operation": "QueryWorkflow", "description": "Sends a Query to read a Workflow Execution's state.", "effect_of_throttling": "The caller receives the result later.", "is_background": "FALSE" },
    { "operation": "RecordActivityTaskHeartbeat", "description": "Records an Activity Heartbeat by task token.", "effect_of_throttling": "Heartbeats are delayed, which can cause a Heartbeat Timeout even though the Activity is still running.", "is_background": "FALSE" },
    { "operation": "RecordActivityTaskHeartbeatById", "description": "Records an Activity Heartbeat by Workflow ID, Run ID, and Activity ID.", "effect_of_throttling": "Heartbeats are delayed, which can cause a Heartbeat Timeout even though the Activity is still running.", "is_background": "FALSE" },
    { "operation": "RequestCancelWorkflowExecution", "description": "Requests cancellation of a Workflow Execution.", "effect_of_throttling": "The cancellation reaches the Workflow later.", "is_background": "FALSE" },
    { "operation": "ResetActivity", "description": "Restarts an Activity from the beginning.", "effect_of_throttling": "The Activity keeps running until the reset takes effect.", "is_background": "FALSE" },
    { "operation": "ResetStickyTaskQueue", "description": "Clears a Workflow Execution's Sticky Execution affinity to a Worker.", "effect_of_throttling": "Workflow Tasks stay bound to the previous Worker longer.", "is_background": "FALSE" },
    { "operation": "ResetWorkflowExecution", "description": "Resets a Workflow Execution to an earlier point in its Event History and starts a new run from there.", "effect_of_throttling": "The Workflow Execution continues from its current state until the reset takes effect.", "is_background": "FALSE" },
    { "operation": "RespondActivityTaskCanceled", "description": "Worker confirms that an Activity was canceled, by task token.", "effect_of_throttling": "The Workflow waits longer for the confirmation.", "is_background": "FALSE" },
    { "operation": "RespondActivityTaskCanceledById", "description": "Worker confirms that an Activity was canceled, by Activity ID.", "effect_of_throttling": "The Workflow waits longer for the confirmation.", "is_background": "FALSE" },
    { "operation": "RespondActivityTaskCompleted", "description": "Worker returns an Activity result, by task token.", "effect_of_throttling": "The Workflow's next step is delayed.", "is_background": "FALSE" },
    { "operation": "RespondActivityTaskCompletedById", "description": "Worker returns an Activity result, by Activity ID.", "effect_of_throttling": "The Workflow's next step is delayed.", "is_background": "FALSE" },
    { "operation": "RespondActivityTaskFailed", "description": "Worker reports an Activity failure, by task token.", "effect_of_throttling": "Retries and compensation logic are delayed.", "is_background": "FALSE" },
    { "operation": "RespondActivityTaskFailedById", "description": "Worker reports an Activity failure, by Activity ID.", "effect_of_throttling": "Retries and compensation logic are delayed.", "is_background": "FALSE" },
    { "operation": "RespondNexusTaskCompleted", "description": "Worker returns a successful Nexus Task result.", "effect_of_throttling": "Completion of the Nexus call is delayed.", "is_background": "FALSE" },
    { "operation": "RespondNexusTaskFailed", "description": "Worker reports a Nexus Task failure.", "effect_of_throttling": "Error handling is delayed.", "is_background": "FALSE" },
    { "operation": "RespondQueryTaskCompleted", "description": "Worker returns a Query result.", "effect_of_throttling": "The Client waits longer for the result.", "is_background": "FALSE" },
    { "operation": "RespondWorkflowTaskCompleted", "description": "Worker returns new Commands after completing a Workflow Task.", "effect_of_throttling": "The Temporal Service applies the Commands later.", "is_background": "FALSE" },
    { "operation": "RespondWorkflowTaskFailed", "description": "Worker reports a Workflow Task failure.", "effect_of_throttling": "The retry of the Workflow Task is delayed.", "is_background": "FALSE" },
    { "operation": "SetCurrentDeployment", "description": "Sets the current Worker Deployment for a Task Queue.", "effect_of_throttling": "The switch to the new version is delayed.", "is_background": "FALSE" },
    { "operation": "SetCurrentDeploymentVersion", "description": "Sets the current Build ID version.", "effect_of_throttling": "The rollout is held.", "is_background": "FALSE" },
    { "operation": "SetWorkerDeploymentCurrentVersion", "description": "Sets the current version of a Worker Deployment.", "effect_of_throttling": "The Worker Deployment stays on the previous version.", "is_background": "FALSE" },
    { "operation": "SetWorkerDeploymentRampingVersion", "description": "Sets the ramp percentage for a new Worker Deployment Version.", "effect_of_throttling": "The ramp is paused.", "is_background": "FALSE" },
    { "operation": "ShutdownWorker", "description": "Notifies the Temporal Service that a Worker is shutting down.", "effect_of_throttling": "The Worker keeps running longer.", "is_background": "FALSE" },
    { "operation": "SignalWithStartWorkflowExecution", "description": "Sends a Signal to a running Workflow Execution, or starts a new one and sends the Signal.", "effect_of_throttling": "The Signal and the start are both delayed.", "is_background": "FALSE" },
    { "operation": "SignalWorkflowExecution", "description": "Sends a Signal to a Workflow Execution.", "effect_of_throttling": "The Signal arrives later.", "is_background": "FALSE" },
    { "operation": "StartBatchOperation", "description": "Starts a batch operation, such as resetting or terminating many Workflow Executions.", "effect_of_throttling": "The batch operation starts later.", "is_background": "FALSE" },
    { "operation": "StartWorkflowExecution", "description": "Starts a new Workflow Execution.", "effect_of_throttling": "Start latency increases.", "is_background": "FALSE" },
    { "operation": "StateMachineOutbound", "description": "Sends outbound requests generated by the Temporal Service's internal state machines.", "effect_of_throttling": "Outbound requests queue up, which delays their side effects.", "is_background": "TRUE" },
    { "operation": "StateMachineTimer", "description": "Fires Timers managed by the Temporal Service's internal state machines.", "effect_of_throttling": "Timed events fire later.", "is_background": "TRUE" },
    { "operation": "StopBatchOperation", "description": "Stops a batch operation.", "effect_of_throttling": "The batch operation keeps running until the task is processed.", "is_background": "FALSE" },
    { "operation": "TerminateWorkflowExecution", "description": "Terminates a Workflow Execution.", "effect_of_throttling": "The Workflow Execution keeps running longer.", "is_background": "FALSE" },
    { "operation": "TransferActivityTask", "description": "Adds an Activity Task to its Task Queue for a Worker to pick up.", "effect_of_throttling": "Scheduling of the Activity Task is delayed.", "is_background": "TRUE" },
    { "operation": "TransferCancelExecution", "description": "Delivers a cancellation request to the target Workflow Execution.", "effect_of_throttling": "The target Workflow Execution receives the cancellation later.", "is_background": "TRUE" },
    { "operation": "TransferCloseExecution", "description": "Closes a running Workflow Execution.", "effect_of_throttling": "The Workflow Execution stays open longer.", "is_background": "TRUE" },
    { "operation": "TransferResetWorkflow", "description": "Starts a reset of a Workflow Execution.", "effect_of_throttling": "The reset is delayed and the Workflow Execution continues from its current state.", "is_background": "TRUE" },
    { "operation": "TransferSignalExecution", "description": "Delivers a Signal to another Workflow Execution.", "effect_of_throttling": "The Signal arrives later, which delays the logic that depends on it.", "is_background": "TRUE" },
    { "operation": "TransferStartChildExecution", "description": "Starts a Child Workflow Execution.", "effect_of_throttling": "The Child Workflow Execution starts later.", "is_background": "TRUE" },
    { "operation": "TransferWorkflowTask", "description": "Adds a Workflow Task to its Task Queue for a Worker to pick up.", "effect_of_throttling": "Scheduling of the Workflow Task is delayed.", "is_background": "TRUE" },
    { "operation": "TriggerWorkflowRule", "description": "Manually triggers a Worker Versioning rule.", "effect_of_throttling": "The rule takes effect later.", "is_background": "FALSE" },
    { "operation": "UnpauseActivity", "description": "Resumes a paused Activity.", "effect_of_throttling": "The Activity stays paused longer.", "is_background": "FALSE" },
    { "operation": "UpdateActivityOptions", "description": "Changes the Retry Policy or timeouts of a running Activity.", "effect_of_throttling": "The new options take effect later.", "is_background": "FALSE" },
    { "operation": "UpdateSchedule", "description": "Changes the configuration of a Schedule.", "effect_of_throttling": "The new configuration takes effect later.", "is_background": "FALSE" },
    { "operation": "UpdateWorkerDeploymentVersionMetadata", "description": "Updates the metadata on a Worker Deployment Version.", "effect_of_throttling": "The metadata stays out of date longer.", "is_background": "FALSE" },
    { "operation": "UpdateWorkflowExecution", "description": "Sends a Workflow Update to a Workflow Execution.", "effect_of_throttling": "The Update is accepted later.", "is_background": "FALSE" },
    { "operation": "UpdateWorkflowExecutionOptions", "description": "Changes the options of a Workflow Execution.", "effect_of_throttling": "The changes take effect later.", "is_background": "FALSE" },
    { "operation": "UserTimer", "description": "Fires a Timer created in Workflow code.", "effect_of_throttling": "The Timer fires later, including Timers created by a Workflow sleep.", "is_background": "TRUE" },
    { "operation": "VisibilityCloseExecution", "description": "Updates the Visibility record of a Workflow Execution when it closes.", "effect_of_throttling": "List results show the Workflow Execution as open until the task is processed.", "is_background": "TRUE" },
    { "operation": "VisibilityStartExecution", "description": "Creates the Visibility record for a new Workflow Execution.", "effect_of_throttling": "The Workflow Execution is missing from lists in the Web UI and the Temporal CLI until the task is processed.", "is_background": "TRUE" },
    { "operation": "VisibilityUpsertExecution", "description": "Updates the Search Attributes in a Workflow Execution's Visibility record.", "effect_of_throttling": "The Search Attribute changes appear later.", "is_background": "TRUE" },
    { "operation": "WorkflowBackoffTimer", "description": "Timer that delays the start of a Workflow retry or Continue-As-New run according to its backoff.", "effect_of_throttling": "The Workflow Execution starts later than the backoff specifies.", "is_background": "TRUE" },
    { "operation": "WorkflowExecutionTimeout", "description": "Enforces the Workflow Execution Timeout.", "effect_of_throttling": "The Workflow Execution Timeout fires later.", "is_background": "TRUE" },
    { "operation": "WorkflowRunTimeout", "description": "Enforces the Workflow Run Timeout.", "effect_of_throttling": "The Workflow Run Timeout fires later.", "is_background": "TRUE" },
    { "operation": "WorkflowTaskTimeout", "description": "Times out a Workflow Task that a Worker didn't complete in time.", "effect_of_throttling": "The timed-out Workflow Task stays outstanding and its retry is delayed.", "is_background": "TRUE" }
]

export default function OperationsTable() {
    return (
        <DocsTable Columns={["Operation", "Description", "Priority", "Effect of throttling"]} sortable={true}>
            {operations.map((operation) => (
                <DocsTableRow key={operation.operation}>
                    <NewDocsCell>{operation.operation}</NewDocsCell>
                    <NewDocsCell>{operation.description}</NewDocsCell>
                    <NewDocsCell>{operation.is_background == "TRUE" ? "Background" : "Foreground"}</NewDocsCell>
                    <NewDocsCell>{operation.effect_of_throttling}</NewDocsCell>
                </DocsTableRow>
            ))}
        </DocsTable>
    )
}
