name: Typos and Grammar
description: Report typos, spelling mistakes, or grammar issues.
labels: ["copy-editing"]
body:
  - type: checkboxes
    id: employee
    attributes:
      label: Temporal Affiliation
      options:
        - label: I am a Temporal employee
          required: false
  - type: input
    id: issue-url
    attributes:
      label: Page URL
      description: The page where the issue occurs
      placeholder: "For example, https://docs.temporal.io/..."
    validations:
      required: true
  - type: textarea
    id: issue-location
    attributes:
      label: Typo or Grammar Issue
      description: Report typos, spelling mistakes, or grammar problems here. Describe the problem and your recommended solution. Specify an approximate location on the page (for example, under which heading or part of the content), and any other details that will help us locate and resolve the problem.
      placeholder: "Section title, issue, suggested correction"
    validations:
      required: true
  - type: markdown
    attributes:
      value: "Thanks for helping us improve our documentation."
