---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: docs
  label: docs
  create: documents
  match: "**/*"
- type: directory
  path: blog
  label: Blog
  create: documents
  match: "**/*"
upload_dir: static/cms
public_path: "/cms"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: build
  install_dependencies_command: yarn install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: yarn start
