import React from 'react';
import Head from '@docusaurus/Head';
import Layout from '@theme/Layout';
import { CookbookHome } from '@site/src/components';

export default function CookbookLanding() {
  return (
    <Layout title="AI Cookbook" description="AI Cookbook">
      {/* Generated by plugins/cookbook-index's postBuild hook — see MARKDOWN_PIPELINE.md. */}
      <Head>
        <link rel="alternate" type="text/markdown" href="/ai-cookbook.md" title="AI Cookbook" />
      </Head>
      <CookbookHome />
    </Layout>
  );
}
