import React from "react";
import { DocsTable, NewDocsCell, DocsTableRow } from '@site/src/components';

const operations = [
{"operation":"ActivityRetryTimer","description":"Internal timer that schedules the retry of a failed Activity execution.","effect_of_throttling":"Activity retry delayed.","is_background":"TRUE"},
{"operation":"ActivityTimeout","description":"Marks an Activity as timed‑out when its deadline passes.","effect_of_throttling":"Activity task stays in-flight longer and timeout is delayed, so retry is also delayed (if there is a retry).","is_background":"TRUE"},
{"operation":"CompleteNexusOperation","description":"Finalises a Nexus operation after worker response.","effect_of_throttling":"External call clean‑up/commit delayed.","is_background":"FALSE"},
{"operation":"CreateSchedule","description":"Creates a Temporal Schedule (cron‑like trigger).","effect_of_throttling":"Client/SDK receives ResourceExhaustedError, leading to backoff and retry.","is_background":"FALSE"},
{"operation":"CreateWorkflowRule","description":"Adds a worker build‑ID versioning rule for a task queue.","effect_of_throttling":"Rule enforcement is delayed.","is_background":"FALSE"},
{"operation":"DeleteSchedule","description":"Deletes an existing Schedule.","effect_of_throttling":"Schedule may keep firing briefly.","is_background":"FALSE"},
{"operation":"DeleteWorkerDeployment","description":"Deletes a worker deployment record.","effect_of_throttling":"Stale deployment metadata persists longer.","is_background":"FALSE"},
{"operation":"DeleteWorkerDeploymentVersion","description":"Deletes one build‑ID version entry under a deployment.","effect_of_throttling":"Version appears valid until task processed.","is_background":"FALSE"},
{"operation":"DeleteWorkflowExecution","description":"Hard‑deletes workflow history and state.","effect_of_throttling":"Storage is freed later; data visible longer.","is_background":"FALSE"},
{"operation":"DeleteWorkflowRule","description":"Deletes a worker build‑ID rule.","effect_of_throttling":"Rule continues to exist until task handled.","is_background":"FALSE"},
{"operation":"DeprecateNamespace","description":"Marks a namespace as deprecated in cluster metadata.","effect_of_throttling":"Clients still see it as active.","is_background":"FALSE"},
{"operation":"DescribeBatchOperation","description":"Returns metadata for a batch operation.","effect_of_throttling":"Admin/UI read waits longer.","is_background":"FALSE"},
{"operation":"DescribeDeployment","description":"Shows worker deployment details.","effect_of_throttling":"Info retrieval is delayed.","is_background":"FALSE"},
{"operation":"DescribeNamespace","description":"Returns namespace configuration.","effect_of_throttling":"Admin read waits.","is_background":"FALSE"},
{"operation":"DescribeSchedule","description":"Reads a Schedule’s current state.","effect_of_throttling":"Call responds slower.","is_background":"FALSE"},
{"operation":"DescribeTaskQueue","description":"Returns stats and configuration of a task queue.","effect_of_throttling":"Monitoring dashboards lag.","is_background":"FALSE"},
{"operation":"DescribeWorkerDeployment","description":"Shows details of a specific worker deployment.","effect_of_throttling":"Same delay in status.","is_background":"FALSE"},
{"operation":"DescribeWorkerDeploymentVersion","description":"Shows a particular build‑ID version record.","effect_of_throttling":"Detail retrieval delayed.","is_background":"FALSE"},
{"operation":"DescribeWorkflowExecution","description":"Returns high‑level info for a workflow execution.","effect_of_throttling":"Diagnostics/CLI wait longer.","is_background":"FALSE"},
{"operation":"DescribeWorkflowRule","description":"Reads a worker versioning rule.","effect_of_throttling":"Admin tools wait.","is_background":"FALSE"},
{"operation":"DispatchByEndpoint","description":"Routes a Nexus task to workers by endpoint name.","effect_of_throttling":"Task routing latencies increase.","is_background":"FALSE"},
{"operation":"DispatchByNamespaceAndTaskQueue","description":"Routes a Nexus task by namespace and task queue.","effect_of_throttling":"Same: Nexus task starts later.","is_background":"FALSE"},
{"operation":"ExecuteMultiOperation","description":"Runs a compound operation.","effect_of_throttling":"Operation is delayed","is_background":"FALSE"},
{"operation":"GetClusterInfo","description":"Returns information about cluster capabilities and versions.","effect_of_throttling":"CLI/API calls take longer.","is_background":"FALSE"},
{"operation":"GetCurrentDeployment","description":"Fetches the cluster‑wide current worker deployment.","effect_of_throttling":"Rollout tooling sees stale info.","is_background":"FALSE"},
{"operation":"GetSearchAttributes","description":"Lists custom search attribute definitions.","effect_of_throttling":"SDK/CLI wait.","is_background":"FALSE"},
{"operation":"GetSystemInfo","description":"Returns system build & feature info.","effect_of_throttling":"Diagnostic call delayed.","is_background":"FALSE"},
{"operation":"GetWorkerBuildIdCompatibility","description":"Returns build‑ID compatibility matrix for a task queue.","effect_of_throttling":"Rollout decisions wait.","is_background":"FALSE"},
{"operation":"GetWorkerVersioningRules","description":"Lists worker versioning rules.","effect_of_throttling":"Admin listing delayed.","is_background":"FALSE"},
{"operation":"GetWorkflowExecutionHistory","description":"Streams workflow history in forward order.","effect_of_throttling":"History load in UI/CLI is slow.","is_background":"FALSE"},
{"operation":"GetWorkflowExecutionHistoryReverse","description":"Streams history in reverse order.","effect_of_throttling":"Same slower history read.","is_background":"FALSE"},
{"operation":"ListNamespaces","description":"Lists all namespaces in the cluster.","effect_of_throttling":"UI/CLI list paginates slower.","is_background":"FALSE"},
{"operation":"ListScheduleMatchingTimes","description":"Computes future fire‑times for a Schedule.","effect_of_throttling":"Preview takes longer.","is_background":"FALSE"},
{"operation":"ListTaskQueuePartitions","description":"Lists partitions backing a task queue.","effect_of_throttling":"Load‑balancing insight lag.","is_background":"FALSE"},
{"operation":"ListWorkerDeployments","description":"Lists all worker deployments.","effect_of_throttling":"Deployment inventory delayed.","is_background":"FALSE"},
{"operation":"ListWorkflowRules","description":"Lists all build‑ID versioning rules.","effect_of_throttling":"Admin list wait.","is_background":"FALSE"},
{"operation":"PatchSchedule","description":"Modifies an existing Schedule (e.g., add interval).","effect_of_throttling":"Change becomes effective later.","is_background":"FALSE"},
{"operation":"PauseActivity","description":"Server‑side API to pause a long‑running Activity.","effect_of_throttling":"Activity continues running until pause task processed.","is_background":"FALSE"},
{"operation":"PollActivityTaskQueue","description":"Worker long‑poll for Activity tasks.","effect_of_throttling":"Activity poller receives ResourceExhaustedError, leading to automatic backoff and retry, which slows down activity task processing.","is_background":"FALSE"},
{"operation":"PollNexusTaskQueue","description":"Worker long‑poll for Nexus tasks.","effect_of_throttling":"Nexus task poller receives ResourceExhaustedError, leading to automatic backoff and retry, which slows down Nexus task processing.","is_background":"FALSE"},
{"operation":"PollWorkflowExecutionUpdate","description":"Client poll for workflow‑update completion.","effect_of_throttling":"Client waits extra for result.","is_background":"FALSE"},
{"operation":"PollWorkflowTaskQueue","description":"Worker long‑poll for Workflow Tasks.","effect_of_throttling":"Workflow poller receives ResourceExhaustedError, leading to automatic backoff and retry, which slows down workflow progress.","is_background":"FALSE"},
{"operation":"QueryWorkflow","description":"Read‑only query on workflow state.","effect_of_throttling":"Caller receives result later.","is_background":"FALSE"},
{"operation":"RecordActivityTaskHeartbeat","description":"Worker heartbeat for an Activity (by task token).","effect_of_throttling":"Heartbeats delayed, risking false timeout.","is_background":"FALSE"},
{"operation":"RecordActivityTaskHeartbeatById","description":"Same heartbeat call using Activity/Run IDs.","effect_of_throttling":"Same impact.","is_background":"FALSE"},
{"operation":"RequestCancelWorkflowExecution","description":"Client request to cancel a workflow.","effect_of_throttling":"Cancellation propagates later.","is_background":"FALSE"},
{"operation":"ResetActivity","description":"Force‑restarts an Activity from scratch.","effect_of_throttling":"Activity keeps running before reset takes effect.","is_background":"FALSE"},
{"operation":"ResetStickyTaskQueue","description":"Clears workflow’s sticky queue affinity.","effect_of_throttling":"Tasks stay bound to prior worker longer.","is_background":"FALSE"},
{"operation":"ResetWorkflowExecution","description":"Server‑side rewind to past event and continue as new.","effect_of_throttling":"Workflow continues in old state.","is_background":"FALSE"},
{"operation":"RespondActivityTaskCanceled","description":"Worker confirms Activity canceled.","effect_of_throttling":"Workflow waits for ack.","is_background":"FALSE"},
{"operation":"RespondActivityTaskCanceledById","description":"Same by ID.","effect_of_throttling":"Same wait.","is_background":"FALSE"},
{"operation":"RespondActivityTaskCompleted","description":"Worker returns Activity result.","effect_of_throttling":"Workflow next step delayed.","is_background":"FALSE"},
{"operation":"RespondActivityTaskCompletedById","description":"Same by ID.","effect_of_throttling":"Same delay.","is_background":"FALSE"},
{"operation":"RespondActivityTaskFailed","description":"Worker reports Activity failure.","effect_of_throttling":"Retry/compensation delayed.","is_background":"FALSE"},
{"operation":"RespondActivityTaskFailedById","description":"Same by ID.","effect_of_throttling":"Same delay.","is_background":"FALSE"},
{"operation":"RespondNexusTaskCompleted","description":"Worker returns Nexus task success.","effect_of_throttling":"External call completion delayed.","is_background":"FALSE"},
{"operation":"RespondNexusTaskFailed","description":"Worker returns Nexus task failure.","effect_of_throttling":"Error handling delayed.","is_background":"FALSE"},
{"operation":"RespondQueryTaskCompleted","description":"Worker returns query result.","effect_of_throttling":"Client waits longer.","is_background":"FALSE"},
{"operation":"RespondWorkflowTaskCompleted","description":"Worker returns new commands after WFT.","effect_of_throttling":"Workflow commands applied later.","is_background":"FALSE"},
{"operation":"RespondWorkflowTaskFailed","description":"Worker reports WFT failure.","effect_of_throttling":"Retry/new task creation delayed.","is_background":"FALSE"},
{"operation":"SetCurrentDeployment","description":"Sets which worker deployment is current for a queue.","effect_of_throttling":"Version switch postponed.","is_background":"FALSE"},
{"operation":"SetCurrentDeploymentVersion","description":"Sets current build‑ID version number.","effect_of_throttling":"Rollout holds.","is_background":"FALSE"},
{"operation":"SetWorkerDeploymentCurrentVersion","description":"Sets version for a specific deployment.","effect_of_throttling":"Deployment stays on old version.","is_background":"FALSE"},
{"operation":"SetWorkerDeploymentRampingVersion","description":"Sets percentage ramp for new version.","effect_of_throttling":"Canary rollout paused.","is_background":"FALSE"},
{"operation":"ShutdownWorker","description":"Gracefully shuts down a running worker via server call.","effect_of_throttling":"Worker keeps running a bit longer.","is_background":"FALSE"},
{"operation":"SignalWithStartWorkflowExecution","description":"Signals an existing run or starts a new one with a signal.","effect_of_throttling":"Signal/start both delayed.","is_background":"FALSE"},
{"operation":"SignalWorkflowExecution","description":"Sends an asynchronous signal to a workflow.","effect_of_throttling":"Signal arrives late.","is_background":"FALSE"},
{"operation":"StartBatchOperation","description":"Starts a batch admin operation (e.g., bulk reset).","effect_of_throttling":"Batch begins later.","is_background":"FALSE"},
{"operation":"StartWorkflowExecution","description":"Creates a new workflow run.","effect_of_throttling":"Start latency increases.","is_background":"FALSE"},
{"operation":"StateMachineOutbound","description":"Emits outbound commands generated by the new state‑machine core.","effect_of_throttling":"Commands queue up, deferring their side‑effects.","is_background":"TRUE"},
{"operation":"StateMachineTimer","description":"Fires timers managed by the state‑machine core.","effect_of_throttling":"Timed events (e.g., sleeps) occur later.","is_background":"TRUE"},
{"operation":"StopBatchOperation","description":"Stops/cancels a batch operation.","effect_of_throttling":"Batch keeps working until task processed.","is_background":"FALSE"},
{"operation":"TerminateWorkflowExecution","description":"Force‑terminates a workflow run.","effect_of_throttling":"Workflow continues running longer.","is_background":"FALSE"},
{"operation":"TransferActivityTask","description":"Dispatches an Activity task to a worker on its task queue.","effect_of_throttling":"Activity task schedule is delayed.","is_background":"TRUE"},
{"operation":"TransferCancelExecution","description":"Sends a cancel request to the target workflow.","effect_of_throttling":"Target workflow receives the cancel later.","is_background":"TRUE"},
{"operation":"TransferCloseExecution","description":"Close a running workflow execution","effect_of_throttling":"Workflow remains open.","is_background":"TRUE"},
{"operation":"TransferResetWorkflow","description":"Initiates a reset of a workflow’s state/history.","effect_of_throttling":"Reset is postponed; old state continues.","is_background":"TRUE"},
{"operation":"TransferSignalExecution","description":"Delivers a signal event to another workflow.","effect_of_throttling":"Signal arrives late, delaying downstream logic.","is_background":"TRUE"},
{"operation":"TransferStartChildExecution","description":"Starts a configured child workflow run.","effect_of_throttling":"Child workflow starts later than expected.","is_background":"TRUE"},
{"operation":"TransferWorkflowTask","description":"Schedules a Workflow Task for workers.","effect_of_throttling":"Workflow task schedule is delayed.","is_background":"TRUE"},
{"operation":"TriggerWorkflowRule","description":"Manually triggers a worker build‑ID rule.","effect_of_throttling":"Trigger effect deferred.","is_background":"FALSE"},
{"operation":"UnpauseActivity","description":"Resumes a previously paused Activity.","effect_of_throttling":"Activity remains paused longer.","is_background":"FALSE"},
{"operation":"UpdateActivityOptions","description":"Updates retry/timeout options of a running Activity.","effect_of_throttling":"New options take effect later.","is_background":"FALSE"},
{"operation":"UpdateSchedule","description":"Updates fields of an existing Schedule.","effect_of_throttling":"Updated schedule behavior delayed.","is_background":"FALSE"},
{"operation":"UpdateWorkerDeploymentVersionMetadata","description":"Updates metadata on a deployment version.","effect_of_throttling":"Metadata remains outdated.","is_background":"FALSE"},
{"operation":"UpdateWorkflowExecution","description":"Server‑side update (workflow update API).","effect_of_throttling":"Update is accepted later.","is_background":"FALSE"},
{"operation":"UpdateWorkflowExecutionOptions","description":"Changes execution options (memo, search attributes).","effect_of_throttling":"Option changes visible later.","is_background":"FALSE"},
{"operation":"UserTimer","description":"Fires a user‑defined timer created inside a workflow.","effect_of_throttling":"User timer (including workflow sleep) fire event delayed.","is_background":"TRUE"},
{"operation":"VisibilityCloseExecution","description":"Updates a closed workflow in Visibility store.","effect_of_throttling":"Closed workflow remains open in list workflow visibility API results until task is processed.","is_background":"TRUE"},
{"operation":"VisibilityStartExecution","description":"Creates a record for the workflow in Visibility store.","effect_of_throttling":"New run is absent from lists in UI and CLI output until task processed.","is_background":"TRUE"},
{"operation":"VisibilityUpsertExecution","description":"Updates search attributes for a workflow run.","effect_of_throttling":"Search attribute update is delayed.","is_background":"TRUE"},
{"operation":"WorkflowBackoffTimer","description":"Timer that delays retry or continued‑as‑new start per backoff policy.","effect_of_throttling":"Workflow start delayed beyond intended backoff time.","is_background":"TRUE"},
{"operation":"WorkflowExecutionTimeout","description":"Enforces the max total execution duration of a workflow.","effect_of_throttling":"Timeout of workflow execution chain is delayed.","is_background":"TRUE"},
{"operation":"WorkflowRunTimeout","description":"Enforces timeout of an individual workflow run.","effect_of_throttling":"Timeout on workflow run is delayed.","is_background":"TRUE"},
{"operation":"WorkflowTaskTimeout","description":"Times out a Workflow Task that a worker hasn’t completed in time.","effect_of_throttling":"Timeout workflow task remains outstanding; retried workflow task is delayed.","is_background":"TRUE"}
]

    export default function OperationsTable() {
        return (
            <DocsTable Columns={["Operation", "Description", "Priority", "Effect of Throttling"]} sortable={true}>
                {operations.map((operation) => (
                    <DocsTableRow key={operation.operation}>
                        <NewDocsCell>{operation.operation}</NewDocsCell>
                        <NewDocsCell>{operation.description}</NewDocsCell>
                        <NewDocsCell>{operation.is_background == "TRUE" ? "Foreground" : "Background"}</NewDocsCell>
                        <NewDocsCell>{operation.effect_of_throttling}</NewDocsCell>
                    </DocsTableRow>
                ))}
            </DocsTable>
        )
    }