name: Continuous Integration

# This action works with pull requests and pushes
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout on push
        # github object: https://docs.github.com/en/actions/learn-github-actions/contexts#github-context
        # event names: https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows
        if: "github.event_name == 'push'"
        uses: actions/checkout@v2

      - name: Checkout on PR
        if: "github.event_name == 'pull_request'"
        uses: actions/checkout@v2
        with:
          # Make sure the actual branch is checked out when running on pull requests
          # event.pull_request: https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#pull_request
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Prettify code
        uses: creyD/prettier_action@v3.3
        with:
          # This part is also where you can pass other options, for example:
          prettier_options: --write **/*.{js,md}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
