name: Check formatting

on:
  # runs when a pull request is opened or reopened or when the head branch of the pull request is updated
  pull_request:

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v3
      with:
        repository: ${{ github.event.pull_request.head.repo.full_name }}
        ref: ${{ github.head_ref }}

    - uses: actions/setup-node@v1

    - name: Check formatting
      # if this PR is from a fork
      if: ${{ github.event.pull_request.head.repo.full_name != github.repository }}
      run: npx dprint check

    - name: Format
      # if this PR isn't from a fork
      if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
      run: npx dprint fmt

    - name: Commit changes
      # if this PR isn't from a fork
      if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Format