name: reviewdog
on: [pull_request]

jobs:
  vale:
    name: runner / vale
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get changed files
        id: files
        run: |
          echo "::set-output name=files::$(git diff --name-only HEAD^ HEAD)"
      - name: Lint files
        uses: errata-ai/vale-action@reviewdog
        with:
          files: ${{ steps.files.outputs.files }}
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
