name: Vale CI

on:
  pull_request:
    paths:
      - "docs/**"

permissions:
  contents: read
  pull-requests: write

jobs:
  vale:
    name: Lint prose
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: vale-cli/vale-action@v2.1.1
        with:
          reporter: github-pr-review
          level: info
          filter_mode: diff_context
          fail_on_error: false
          vale_flags: "--config=.vale-ci.ini"
